services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes: # For development
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080 # Example
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
